### ISSUE TITLE
Issue with not storing Settings is back

### ISSUE THREAD

**Issue by kpeters58** [ChrisRfr/IceDesign#4]
1.9.4: For instance, 'Add window name to var/constant', 'Use short names for controls'

**Comment by ChrisRfr** [comment]
It's old now, sorry, I must have missed something when I added the new parameters.
Is the issue still relevant ?

**Comment by kpeters58** [comment]
Seems you fixed it - all good - thanks!

Kind regards,
Kai

Sent with [Proton Mail](https://proton.me/) secure email.
