### ISSUE TITLE
Feature request - remember window position & size

### ISSUE THREAD

**Issue by kpeters58** [ChrisRfr/IceDesign#5]
Hi Chris,

the designer consistently pops up half off my first screen on my dual screen setup which annoys me to no end.
Could you please add persistence for positions & size of the application?

Thanks much!

**Comment by ChrisRfr** [comment]
Hi Peters,
I realized this weekend that I had 2 issues, including an old one that I hadn't seen and I didn't receive any notification.
As the author, it's strange that notifications aren't set to On by default, damned Github!
While googling , I found where to subscribe see the image below.

No matter, the bad positioning should be solved now by recentering IceDesign after the 1st initialization resizing.

![Github_Notification_Issues](https://github.com/ChrisRfr/IceDesign/assets/4269099/2929bf2e-259f-4e2b-bde4-e89b42bf055a)

**Comment by kpeters58** [comment]
Hi Chris,

with the latest release from today, the exe window is now screen centered, but x, y, h, w are not remembered. This is definitely better than before, but remembering/setting these 4 would be even nicer.

Kind regards,
Kai

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by kpeters58** [comment]
Hi Chris,

just installed today's release.

It now nicely & correctly remembers the window size. I don't know if you have aimed for position as well?

If you did, then that's not working: Size is remembered, but not position. It also always displays on the main monitor in a multi-monitor setup, even if I move it to a secondary monitor and close it there.

Kind regards,
Kai

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by ChrisRfr** [comment]
Hi Kai,
I now save the position of IceDesign window, including in multi-monitors, in IceDesign.ini, in addition to the window size.
So that I can reuse the same position at the next restart. Will be in next update.
Regards,
Chris

**Comment by kpeters58** [comment]
Thanks Chris,

you just made an already awesome product even better - much appreciated!

Kind regards,
Kai

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by ChrisRfr** [comment]
Thanks for the idea and for insisting. 
I don't know why I didn't do it sooner, it's fine.
