### ISSUE TITLE
License view corrupt + Variables Suffix-Option without function

### ISSUE THREAD

**Issue by SIRprise** [ChrisRfr/IceDesign#6]
Hi, I'm testing v2.1.1 Demo. Nice tool!
Here are 2 screenshots to show the little problems:
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/b9c9eadc-ff53-494d-8af2-4086e31640ce)

The license windows seems to be showed only if window is not maximized an my 4k screen:
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/e8a11680-1aaa-4902-85f4-ec118ba6dd26)

**Comment by ChrisRfr** [comment]
Hi SIRprise,
As currently defined, the suffix is only used for variable declarations to define the type .i (integer) (ex: Global SIRWindow_0.i) 
But then, I agree, it's not very clear and not really useful.  
It would be better with the string (SIR in your example) as a prefix or suffix, if checked (Window_0SIR) 
If I've understood correctly ? 

For the license, I don't have a HiDPI screen to test.
It's very strange and I don't really understand why you have this! 
It works well here with a scale of 100, 125, 150 or 175%, the WebGadget is correctly resized with the Html text properly displayed.
I added a style for the html and the body, it'll probably be better 
```
<html style="margin:10px;height:95%;width:95%">"
<body style="margin:10px;min-height:95%;width:95%">"
```

**Comment by SIRprise** [comment]
Hi Chris,
thanks for the explanation.  I would assume SIRPanel_1 becomes PanelSIR_1 or Panel_1SIR if the suffix button has been checked.

My screen is a 4k (3840x2160) with 150% scale. The WebGadget isn't displayed right if the width of the window is not at minimum.
Here is an example if I make it slidely wider:
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/1cc0ba01-4a1c-4b46-9632-af223b11208c)
So I guess there is an anchor not set right. I think the anchor of some inner element is set to the outer window instead to the left border of the settings menu (if it is open).
Edit:
It seems to be not the webgadget: If I mark some text, it looks like this:
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/ec82ff2c-62bd-4f32-b17f-ae63a14363bc)

**Comment by ChrisRfr** [comment]
Hi, it's made for Prefix, Suffix and Add Short Window Name.
I made a few adjustments to the license included in a WebGadget.
But since I'm not reproducing the display defect, can you tell me how it looks now ?

**Comment by SIRprise** [comment]
The license view seems to be ok, if "Maxi Design in 4k" is checked, otherwise nothing changed. I also see no other changes in sizing.
Thanks for the options with Prefix and Suffix. It seems to have an effect now. Thank you! :-)
The dropdown with the different options for ordering prefix/suffix/gadget/winname seems to have no effect: The name of the Button is always #PREBtn_1POST (with configured prefix "PRE" and suffix "POST"). Is it a click dummy? I like it!

I translated it to german... some labels are a bit small (can't translate "sort" or "spaces" in settings menu). The first section (language / author) seems to be overwritten at start of the tool. It's a little bit mixed now... The "Declare"-comment in code seems to have no entry in the lang-file.
I had to rename file cause .lang-files are not accepted by github.
[IceDesign.lang.txt](https://github.com/ChrisRfr/IceDesign/files/15446966/IceDesign.lang.txt)

**Comment by ChrisRfr** [comment]
Hi SIRprise,
The dropdown with the different options for ordering prefix/winname/gadget/suffix is only useful if you activate the “Add Window Name” option.
The prefix is always a prefix, so it comes before the gadget name, and the same goes for the suffix, which always comes after. Only the place of the short Window name changes.

Example with #Window_Main (Short name = Main) and a button #Button_OK. And in Settings, “Add Window Name” enabled, Prefix "Pre_" and suffix "_Post",  it will give:
```
WinName+Prefix+Gadget+Suffix: Main_Pre_Button_OK_Post
Prefix+WinName+Gadget+Suffix: Pre_Main_Button_OK_Post
Prefix+Gadget+WinName+Suffix: Pre_Button_OK_Main_Post
Prefix+Gadget+Suffix+WinName: Pre_Button_OK_PostMain
```

Thank you very much for the German translation, I'll look at it as soon as I have time and add the language.

**Comment by SIRprise** [comment]
OK - it took a while and finaly I got it! :)
I own the full version now (but keep my name anonymous, please): Is the PBForm2IceDesign still working (it says "PB-Version: 5.73 x64/x86")? The ConcatMultiLang.exe is useful if I enable multi-language, I guess.
The license view seems to be random working: If I maximize, unmaximize sometimes it works correctly, sometimes not. Whatever, I don't care about.
The translation maybe isn't perfect... I noticed I never translated a design program and wasn't sure where the words would be displayed exactly. I also kept some words (e.g. "bind events") in english, because it would be confusing because nobody uses the german words outside of informatics lesson at school. So... feel free to ask another german guy to verify.
Ticket can be closed! Thanks for your support! :)

**Comment by ChrisRfr** [comment]
I'll probably understand better about the license display issue when I get a HiDPI screen. It works here (even with 175% DPI), I can't reproduce it and I'm still in a fog.
Thanks SIRprise, I close the ticket,

**Comment by SIRprise** [comment]
fyi
There seems to be a bug in PB - it is fixed in the new beta: https://www.purebasic.fr/english/viewtopic.php?t=85205 
Maybe it caused the rendering issues, too.
