### ISSUE TITLE
Invalid code if suffix option used

### ISSUE THREAD

**Issue by SIRprise** [ChrisRfr/IceDesign#7]
I'm sorry to just reopen a new ticket, but this one seems to be a real bug:
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/31fef061-8f61-4956-811e-1bdd8adb2289)
The error message is shown if you try to preview.
[GUIDesign.zip](https://github.com/ChrisRfr/IceDesign/files/15472673/GUIDesign.zip)
It is caused by declaring the constants name in enumeration but forget(?) to use the postfix in the code below. Quickfix is to clear the string in suffix.

`Enumeration MenuItems
  #PREMenu_NewPOST
  #PREMenu_OpenPOST
  #PREMenu_SavePOST
EndEnumeration`

vs

`ToolBarImageButton(#PREMenu_New, ImageID(Image), #PB_ToolBar_Normal, "Neu")
    FreeImage(Image)
    Image = CatchImage(#PB_Any, ?ToolBarIcon_Open)
    ToolBarImageButton(#PREMenu_Open, ImageID(Image), #PB_ToolBar_Normal, "Öffnen")
    FreeImage(Image)`

**Comment by ChrisRfr** [comment]
Thanks, I reproduced it and it should be fixed for the next update.

**Comment by SIRprise** [comment]
thx
