### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by Manuallly-Installed** [ChrisRfr/IceDesign#8]
Windows 10 64 bit / Paid version of IceDesign x64 version 2.1.6
![IceDesign2 16Error](https://github.com/ChrisRfr/IceDesign/assets/84278525/d6a6ba4d-8e91-45f6-a8e7-125f3c20a2ac)

I created a simple 1200x800 window with black background color. 3 buttons in center equally 100 pixels apart from each other on top of each other. At the Top 20 pixels down in the center of the window is the title with yellow front color and black back color. The font I am using is a true-type font downloaded from the internet. I get the following error when I click "Preview" button in the upper right corner of IceDesigner 2.1.6:

Fail to compile:
PBcompiler.exe Temp\~IceDesign_kzq613.pb -e
Temp\~IceDesign_kzq613.exe

Error: Line 32 - Garbage at the end of the line.

**Comment by Manuallly-Installed** [comment]
I experimented with a normal windows font "Arial" for the textgadget and all 3 buttons and I don't get an error. I downloaded the font used in the previous post example from the following website. [https://int10h.org/oldschool-pc-fonts/fontlist/](url)

**Comment by ChrisRfr** [comment]
Hi Manuallly-Installed,
When you have the error, save the form and share it with me, please. 
It allows me to have the same configuration and to reproduce. What is the Font name ?

**Comment by Manuallly-Installed** [comment]
I posted an issue on the Github site. It seems that the font used was the issue because I switched the font to a normal windows font "Arial" and it worked. I included a link to the website I got the font from on the Github issue posts. I need the font to work with IceDesign if possible. Why the font doesn't work with IceDesign I don't know, it is a True-Type font.

I will send you the saved file in a couple of hours when I get a minute. If I can, I will also send the font.

Thank you Brian

Sent from Proton Mail Android

-------- Original Message --------

**Comment by ChrisRfr** [comment]
It is probably just the font name, the generated constant uses this name, ex: 
LoadFont(#Font_Arial_10_B, "Arial", 10, #PB_Font_Bold)

In PureBasic, for constants, the 1st char must be alpha (a-z, A-Z, _) and alphanumeric for subsequent characters (a-z, A-Z ,0-9, _). Hyphens (-) are not allowed.
I'll probably have to add a check to create the right constant name with only the characters allowed from the font name. I mean for example "Arial-2y" : LoadFont(#Font_Arial2y_10_B, "Arial-2y", 10, #PB_Font_Bold).

Thank you in advance for the saved form (.icef) and the font used. It's late here, I'm going to bed.

**Comment by Manuallly-Installed** [comment]
In the attached zip file you will find the saved IceDesign file and the font used when the fail happened. Also, in the image shows the installed font name highlighted.

In PureBasic the file name is shown like this:  **LoadFont(0, "Mx437 HP 100LX 6x8", 10, #PB_Font_Bold)**
If you include the **.ttf** extension at the end of the font file name PureBasic doesn't like it. You don't need the word "**Regular**" in the name either, PureBasic doesn't like it either. The above example loading the font works in PureBasic.

![InstalledFont](https://github.com/ChrisRfr/IceDesign/assets/84278525/a7da2bc3-ef65-4e7f-9808-d2f334b8d714)

[SavedFile&Font.zip](https://github.com/user-attachments/files/15523992/SavedFile.Font.zip)

**Comment by ChrisRfr** [comment]
Thanks for the attached zip file.
It's Indeed the font constant name that doesn't work, the @ character is not allowed in the constant name

> #Font_@Mx437HP100LX6x8_20_B should be #Font_Mx437_HP_100LX_6x8_20_B
> #Font_@Mx437HP100LX6x8_10 should be #Font_Mx437_HP_100LX_6x8_10

It should give for font loading

> LoadFont(#Font_Mx437_HP_100LX_6x8_20_B, "@Mx437 HP 100LX 6x8", 20, #PB_Font_Bold)
> LoadFont(#Font_Mx437_HP_100LX_6x8_10, "@Mx437 HP 100LX 6x8", 10)

I'll fix it as soon as I can by removing the non-allowed characters in the generated constant names.

**Comment by ChrisRfr** [comment]
constant  and variable names are fixed in version 2.1.7
